This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./presentation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file presentation.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file presentation.acr....done (6 lines written, 0 warnings).
Output written in presentation.acr.
Transcript written in presentation.alg.
