This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./tesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file tesis.acn....done (186 entries accepted, 0 rejected).
Sorting entries.....done (1555 comparisons).
Generating output file tesis.acr....done (99 lines written, 0 warnings).
Output written in tesis.acr.
Transcript written in tesis.alg.
